name: PermissionFinder
main: me.HariboPenguin.PermissionFinder.PermissionFinder
version: 1.1
author: HariboPenguin
description: Easily find permission nodes for plugins.
commands:
  findperms:
    description: Find the permission nods for a plugin.
    usage: /findperms [Plugin Name] <Search Term>
  dumpperms:
    description: Dump permission nodes for a plugin to a text file.
    usage: /dumpperms [Plugin Name]
permissions:
  permissionfinder.findperms:
    description: Gives access to the findperms command.
    default: op
  permissionfinder.dumpperms:
    description: Gives access to the dumpperms command.
    default: op